services:
  db_front:
    image: postgres:16
    environment:
      POSTGRES_DB: alumni_front_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alumni
    volumes:
      - db_data_front:/var/lib/postgresql/data
    ports:
      - "5442:5432"

  zookeeper_alumni:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka_alumni:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    depends_on:
      - zookeeper_alumni
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_alumni:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: schema-registry
    depends_on:
      - kafka_alumni
    ports:
      - "8082:8082"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8082

  app_front:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - db_front
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db_front:5432/alumni_front_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: alumni
      QUARKUS_FLYWAY_MIGRATE_AT_START: true
    ports:
      - "8081:8080"

volumes:
  db_data_front: