services:
  db:
    image: postgres16
    environment:
      POSTGRES_DB: alumni_front_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alumni
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5442:5432"
    
  app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/alumni_front_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: alumni
      QUARKUS_FLYWAY_MIGRATE_AT_START: true
    ports:
      - "8081:8080"

volumes:
  db_data: